# Generated by Django 5.0.3 on 2025-04-27 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_start_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recorded_end_time', models.DateTimeField(blank=True, null=True)),
                ('server_player', models.IntegerField(blank=True, null=True)),
                ('team1_score_at_start', models.CharField(blank=True, max_length=10, null=True)),
                ('team2_score_at_start', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_time_ms', models.PositiveIntegerField(help_text='Milliseconds since point start')),
                ('timestamp_abs', models.DateTimeField(auto_now_add=True, help_text='Absolute time coord was saved')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='backend.point')),
            ],
            options={
                'ordering': ['relative_time_ms'],
            },
        ),
    ]
