services:
  # React App Container
  tracker-react:
    build:
      context: .
      dockerfile: Dockerfile.react  # The Dockerfile for React app
    container_name: tracker-react
    restart: always
    ports:
      - "5173:5173"  # React app port
    volumes:
      - ./frontend:/workspace/frontend  # React app directory
      - ./frontend/node_modules:/workspace/frontend/node_modules  # Node modules directory
    networks:
      - traefik_network
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blender-react.rule=Host(`blenderUI.benjaminf.net`)"
      - "traefik.http.services.blender-react.loadbalancer.server.port=80"  # React frontend
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [compute, video, graphics, utility, gpu]

  # Blender Container
  tracker_blender:
    build:
      context: .  # Reference to current directory for building the custom Blender image
      dockerfile: Dockerfile.blender  # Dockerfile used to build the Blender image
    container_name: tracker_blender
    security_opt:
      - seccomp:unconfined  # Allows Blender to run without security restrictions
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DISPLAY=:1  # Ensure correct display environment for Blender
      - HOME=/config
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - TERM=xterm
    volumes:
      - ./config:/config  # Ensure local config directory is mapped properly
      - ./workspace:/workspace  # Mount the workspace for Blender files
    ports:
      - "3002:3000"  # Blender web interface port
      - "3003:3001"  # Another port for Blender (if needed)
    restart: unless-stopped
    networks:
      - traefik_network
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blender.rule=Host(`blender.benjaminf.net`)"
      - "traefik.http.services.blender.loadbalancer.server.port=3000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, video, graphics, utility, display]

  tracker_mysql:
    image: mysql:8.0
    container_name: tracker_mysql
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - internal  # Only accessible within this private network

networks:
  traefik_network:
    external: true
  internal:
    internal: true  # Private network, only accessible by defined services
