services:
  # React App Container (unchanged)
  tracker_react:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: tracker_react
    restart: always
    env_file:
      - .env
    volumes:
      - ./frontend:/workspace/frontend
      - ./frontend/node_modules:/workspace/frontend/node_modules
    networks:
      - traefik_network
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.tennis-tracker-react.rule=Host(`TennisTracker.benjaminf.net`)"
      - "traefik.http.routers.tennis-tracker-react.entrypoints=websecure"
      - "traefik.http.routers.tennis-tracker-react.tls.certresolver=myresolver"
      - "traefik.http.services.tennis-tracker-react.loadbalancer.server.port=80"

  # Blender Container (unchanged)
  tracker_blender:
    build:
      context: .
      dockerfile: Dockerfile.blender
    container_name: tracker_blender
    env_file:
      - .env
    volumes:
      - ./config:/config
      - ./workspace:/workspace
    ports:
      - "55001:55001"
    restart: unless-stopped
    networks:
      - traefik_network
      - internal
    command: /workspace/startBlender.sh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blender.rule=Host(`blender.benjaminf.net`)"
      - "traefik.http.services.blender.loadbalancer.server.port=55001"

  tracker_mysql:
    image: mysql:8.0
    container_name: tracker_mysql
    restart: unless-stopped
    ports:
      - "3309:3306"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - internal
      - bridge

  tracker_mqtt:
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    container_name: tracker_mqtt
    restart: unless-stopped
    ports:
      - "1884:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      - internal
      - bridge

  # --- REMOVED tracker_redis service ---

  tracker_django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: tracker_django
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend/config:/app/backend/config
    networks:
      - internal
      - traefik_network
    depends_on:
      - tracker_mysql # Only depends on MySQL now

    labels:
      # Traefik labels remain the same as they point to Daphne on port 8000
      - "traefik.enable=true"
      # --- Explicitly tell Traefik which network to use for this service ---
      - "traefik.docker.network=traefik_network"
      - "traefik.http.services.tennis-tracker-django.loadbalancer.server.port=8000"
      - "traefik.http.routers.tennis-tracker-django-http.rule=Host(`TennisTracker.benjaminf.net`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/static`))"
      - "traefik.http.routers.tennis-tracker-django-http.entrypoints=websecure"
      - "traefik.http.routers.tennis-tracker-django-http.tls.certresolver=myresolver"
      - "traefik.http.routers.tennis-tracker-django-http.service=tennis-tracker-django"
      - "traefik.http.routers.tennis-tracker-django-ws.entrypoints=websecure"
      - "traefik.http.routers.tennis-tracker-django-ws.tls.certresolver=myresolver"
      - "traefik.http.routers.tennis-tracker-django-ws.service=tennis-tracker-django"

networks:
  traefik_network:
    external: true
  internal:
    internal: true
  bridge:
    internal: false