services:
  # React App Container (unchanged)
  tracker_react:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: tracker_react
    restart: always
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/workspace/frontend
      - ./frontend/node_modules:/workspace/frontend/node_modules
    networks:
      - traefik_network
      - internal
# Inside tracker-react service:
    labels:
      - "traefik.enable=true"
      # --- CHANGE THIS ROUTER ---
      - "traefik.http.routers.tennis-tracker-react.rule=Host(`TennisTracker.benjaminf.net`)" # Use new Host
      - "traefik.http.routers.tennis-tracker-react.entrypoints=websecure" # Assuming HTTPS entrypoint
      - "traefik.http.routers.tennis-tracker-react.tls.certresolver=myresolver" # Your Let's Encrypt resolver name
      - "traefik.http.services.tennis-tracker-react.loadbalancer.server.port=5173" # Internal port Vite dev server runs on (adjust if using nginx/apache in container)

  # Blender Container
  tracker_blender:
    build:
      context: .
      dockerfile: Dockerfile.blender
    container_name: tracker_blender
    env_file:
      - .env
    volumes:
      - ./config:/config
      - ./workspace:/workspace
    ports:
      - "55001:55001" 
    restart: unless-stopped
    networks:
      - traefik_network
      - internal
    command: /workspace/startBlender.sh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blender.rule=Host(`blender.benjaminf.net`)"
      - "traefik.http.services.blender.loadbalancer.server.port=55001"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [compute, video, graphics, utility, display]

  tracker_mysql:
    image: mysql:8.0
    container_name: tracker_mysql
    restart: unless-stopped
    ports:
      - "3309:3306" # no traefik routing here, only exposed port
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - internal
      - bridge
      
  tracker_mqtt:
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    container_name: tracker_mqtt
    restart: unless-stopped
    ports:
      - "1884:1883" # no traefik routing here, only exposed port
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      - internal
      - bridge


  tracker_django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: tracker_django
    restart: unless-stopped
    env_file:
      - .env # Make sure DB creds, SECRET_KEY, DEBUG etc are here
    volumes:
      # Optional: Mount code for development hot-reloading (if needed)
      # - ./backend:/app/backend
      # - ./tracker:/app/tracker
      # Mount supervisor config if not copied in Dockerfile
      - ./backend/config:/app/backend/config
    networks:
      - internal # To talk to MySQL and MQTT
      - traefik_network # To receive requests from Traefik
    depends_on:
      - tracker_mysql # Wait for mysql service to start
    labels:
      - "traefik.enable=true"
      # HTTP Router (API, Admin, Static) - CHANGE HOST
      - "traefik.http.routers.tennis-tracker-django-http.rule=Host(`TennisTracker.benjaminf.net`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/static`))"
      - "traefik.http.routers.tennis-tracker-django-http.entrypoints=websecure"
      - "traefik.http.routers.tennis-tracker-django-http.tls.certresolver=myresolver"
      - "traefik.http.services.tennis-tracker-django-http.loadbalancer.server.port=8000"
      # WebSocket Router - CHANGE HOST
      - "traefik.http.routers.tennis-tracker-django-ws.rule=Host(`TennisTracker.benjaminf.net`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.tennis-tracker-django-ws.entrypoints=websecure"
      - "traefik.http.routers.tennis-tracker-django-ws.tls.certresolver=myresolver"
      - "traefik.http.services.tennis-tracker-django-ws.loadbalancer.server.port=8000"

networks:
  traefik_network:
    external: true
  internal:
    internal: true
  bridge:
    internal: false
