services:
  # React App Container (unchanged)
  tracker-react:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: tracker-react
    restart: always
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/workspace/frontend
      - ./frontend/node_modules:/workspace/frontend/node_modules
    networks:
      - traefik_network
      - internal
# Inside tracker-react service:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracker-react.rule=Host(`benjaminf.net`)" # Main host rule
      - "traefik.http.routers.tracker-react.entrypoints=websecure"
      - "traefik.http.routers.tracker-react.tls.certresolver=myresolver"
      - "traefik.http.services.tracker-react.loadbalancer.server.port=5173" # Port Vite runs on INSIDE container (check Dockerfile.react)

  # Blender Container
  tracker_blender:
    build:
      context: .
      dockerfile: Dockerfile.blender
    container_name: tracker_blender
    env_file:
      - .env
    volumes:
      - ./config:/config
      - ./workspace:/workspace
    ports:
      - "55001:55001" 
    restart: unless-stopped
    networks:
      - traefik_network
      - internal
    command: /workspace/startBlender.sh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blender.rule=Host(`blender.benjaminf.net`)"
      - "traefik.http.services.blender.loadbalancer.server.port=55001"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [compute, video, graphics, utility, display]

  tracker_mysql:
    image: mysql:8.0
    container_name: tracker_mysql
    restart: unless-stopped
    ports:
      - "3309:3306" # no traefik routing here, only exposed port
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - internal
      
  tracker_mqtt:
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    container_name: tracker_mqtt
    restart: unless-stopped
    ports:
      - "1884:1883" # no traefik routing here, only exposed port
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      - internal
      - bridge


  tracker-django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: tracker-django
    restart: unless-stopped
    env_file:
      - .env # Make sure DB creds, SECRET_KEY, DEBUG etc are here
    volumes:
      # Optional: Mount code for development hot-reloading (if needed)
      # - ./backend:/app/backend
      # - ./tracker:/app/tracker
      # Mount supervisor config if not copied in Dockerfile
      - ./backend/config:/app/backend/config
    networks:
      - internal # To talk to MySQL and MQTT
      - traefik_network # To receive requests from Traefik
    depends_on:
      - tracker_mysql # Wait for mysql service to start
    labels:
      - "traefik.enable=true"
      # HTTP Router (for API calls)
      - "traefik.http.routers.tracker-django-http.rule=Host(`benjaminf.net`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/static`))" # Adjust host and paths
      - "traefik.http.routers.tracker-django-http.entrypoints=websecure" # Assuming HTTPS
      - "traefik.http.routers.tracker-django-http.tls.certresolver=myresolver" # Your cert resolver
      - "traefik.http.services.tracker-django-http.loadbalancer.server.port=8000" # Port Daphne/Uvicorn listens on *inside* the container
      # WebSocket Router
      - "traefik.http.routers.tracker-django-ws.rule=Host(`benjaminf.net`) && PathPrefix(`/ws`)" # Adjust host
      - "traefik.http.routers.tracker-django-ws.entrypoints=websecure" # Assuming WSS
      - "traefik.http.routers.tracker-django-ws.tls.certresolver=myresolver" # Your cert resolver
      - "traefik.http.services.tracker-django-ws.loadbalancer.server.port=8000" # Same internal port

networks:
  traefik_network:
    external: true
  internal:
    internal: true
  bridge:
    internal: false
